---
- name: Create grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    restart: true
    user: 1000
    ports:
      - 3000:3000/tcp
    env:
      GF_SECURITY_ADMIN_PASSWORD: 'secret'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - /data/grafana:/var/lib/grafana
