---
- name: Install dependencies
  apt:
    name:
      - gnupg

- name: Install gpg key
  ansible.builtin.get_url:
    url: "https://pgp.mongodb.com/server-6.0.asc"
    dest: "/etc/apt/keyrings/mongo_6.0.asc"
    mode: 0644

- name: Get mongodb repo
  apt_repository:
    repo: >-
      deb [
       arch=amd64,arm64
       signed-by=/etc/apt/keyrings/mongodb-server-6.0.gpg.asc ]
      https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0
      multiverse
    filename: "mongodb-org-6.0"

- name: create mongodb group
  group:
    name: mongodb
    gid: 28
    system: true

- name: Install MongoDB
  apt:
    name: mongodb-org